env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://host.docker.internal:8080
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://host.docker.internal:8080
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: IGNORE
    customMessage: ''
    id: 10016
  - action: IGNORE
    customMessage: ''
    id: 10096
  - action: WARN
    customMessage: ''
    id: 10035
  - action: WARN
    customMessage: ''
    id: 10038
  - action: WARN
    customMessage: ''
    id: 10036
  - action: FAIL
    customMessage: ''
    id: 10021
  - action: FAIL
    customMessage: ''
    id: 40012
  - action: FAIL
    customMessage: ''
    id: 40014
  - action: FAIL
    customMessage: ''
    id: 40018
  - action: FAIL
    customMessage: ''
    id: 90020
  - action: FAIL
    customMessage: ''
    id: 6
  - action: FAIL
    customMessage: ''
    id: 40009
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: /zap/wrk/zap-report.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: /zap/wrk/zap-report.xml
    reportTitle: ZAP Scanning Report
    template: traditional-xml
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: /zap/wrk/zap-report.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
